fix readdir error on folder with many files
Caused due to an earlier incorrect code refactor, resulting in a leftover undefined variable.

Error log:
````
julia> readdir(hdfsclnt, "/user/hadoop/TrueFX")
ERROR: UndefVarError: result not defined
 in _walkdir(::Elly.HDFSClient, ::String, ::Elly.##8#9{Int64,Array{AbstractString,1}}) at /home/hadoop/.julia/v0.5/Elly/src/api_hdfs_base.jl:151
 in readdir at /home/hadoop/.julia/v0.5/Elly/src/api_hdfs_base.jl:298 [inlined]
 in readdir(::Elly.HDFSClient, ::String) at /home/hadoop/.julia/v0.5/Elly/src/api_hdfs_base.jl:297
````

Also added tests for it.